/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.seaglass.SeaGlassLookAndFeel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author aranx
 */
public class EscogerFecha extends javax.swing.JDialog {

    private MostrarBackups parent;

    /**
     * Creates new form EscogerFecha
     */
    public EscogerFecha(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        this.parent = (MostrarBackups) parent;

        //cambiarLookAndFeel(); // CASCA JAVAHELP AL APLICAR EL LOOK AND FEEL
        initComponents();

        setTitle("Escoger fecha");
        // Colocamos la pantalla en el centro del monitor
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) ((screenSize.getWidth() - this.getWidth()) / 2), (int) ((screenSize.getHeight() - this.getHeight()) / 2));
    }

    // Getter del spinner para poder sacar el valor elegido al volver al parent
    public JSpinner getjSpinner_fecha() {
        return jSpinner_fecha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jSpinner_fecha = new javax.swing.JSpinner();
        jButton_aceptarFecha = new javax.swing.JButton();
        jL_eligeFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setBackground(this.parent.backgroundColor());

        jSpinner_fecha.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jSpinner_fecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        jSpinner_fecha.setToolTipText("Fecha seleccionada");

        jButton_aceptarFecha.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jButton_aceptarFecha.setForeground(new java.awt.Color(255, 102, 0));
        jButton_aceptarFecha.setText("Aceptar");
        jButton_aceptarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarFechaActionPerformed(evt);
            }
        });

        jL_eligeFecha.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jL_eligeFecha.setForeground(new java.awt.Color(255, 102, 0));
        jL_eligeFecha.setText("Selecciona una fecha:");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addComponent(jL_eligeFecha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addComponent(jSpinner_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_aceptarFecha)))
                    .addGap(39, 39, 39)))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jL_eligeFecha)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_aceptarFecha)
                        .addComponent(jSpinner_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_aceptarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarFechaActionPerformed
        // Guardamos la fecha elegida, y hacemos la ventana no visible. No la cerramos para poder acceder al valor
        // seleccionado en el spinner desde el parent. Haremos dispose en el método del parent al finalizar.
        this.setVisible(false);
    }//GEN-LAST:event_jButton_aceptarFechaActionPerformed

    public void cambiarLookAndFeel(){      
        try {
            UIManager.setLookAndFeel(SeaGlassLookAndFeel.class.getCanonicalName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EscogerFecha.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(EscogerFecha.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(EscogerFecha.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(EscogerFecha.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptarFecha;
    private javax.swing.JLabel jL_eligeFecha;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSpinner jSpinner_fecha;
    // End of variables declaration//GEN-END:variables
}
